
DROP TABLE TB_LAVAGEM
DROP TABLE TB_OPERADOR
DROP TABLE TB_VEICULO
DROP TABLE TB_MODELO
DROP TABLE TB_MARCA
DROP TABLE TB_CATEGORIA
DROP TABLE TB_SERVICO
GO

CREATE TABLE TB_CATEGORIA
(
    ID_CATEGORIA INT PRIMARY KEY IDENTITY(1,1),
    NM_CATEGORIA VARCHAR(20)
)
GO

CREATE TABLE TB_SERVICO
(
    ID_SERVICO INT PRIMARY KEY IDENTITY(1,1),
    NM_SERVICO VARCHAR(20)
)
GO

CREATE TABLE TB_MARCA
(
    ID_MARCA INT PRIMARY KEY IDENTITY(1,1),
    NM_MARCA VARCHAR(20)
)
GO

CREATE TABLE TB_MODELO
(
    ID_MODELO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    ID_MARCA INT NOT NULL,
    ID_CATEGORIA INT NOT NULL,
    NM_MODELO VARCHAR(40),
    FOREIGN KEY (ID_MARCA) REFERENCES TB_MARCA(ID_MARCA),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES TB_CATEGORIA(ID_CATEGORIA)
)
GO

CREATE TABLE TB_VEICULO
(
    ID_VEICULO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    ID_MODELO INT NOT NULL,
    NM_PLACA VARCHAR(10),
    FOREIGN KEY (ID_MODELO) REFERENCES TB_MODELO(ID_MODELO)
)
GO

CREATE TABLE TB_OPERADOR
(
    ID_OPERADOR INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    NM_OPERADOR VARCHAR(40),
	NM_LOGIN VARCHAR(10)
)
GO

CREATE TABLE TB_LAVAGEM
(
    ID_LAVAGEM INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    VL_LAVAGEM DECIMAL(7,2),
	ID_CATEGORIA INT NOT NULL,
	ID_SERVICO INT NOT NULL,
	FOREIGN KEY (ID_CATEGORIA) REFERENCES TB_CATEGORIA(ID_CATEGORIA),
	FOREIGN KEY (ID_SERVICO) REFERENCES TB_SERVICO(ID_SERVICO)
)
GO

--SEED CATEGORIAS

INSERT INTO TB_CATEGORIA VALUES ('NORMAL')
INSERT INTO TB_CATEGORIA VALUES ('VANPICKUP')
INSERT INTO TB_CATEGORIA VALUES ('CAMINHAO')
GO


--SEED SERVICOS

INSERT INTO TB_SERVICO VALUES ('SIMPLES')
INSERT INTO TB_SERVICO VALUES ('COMPLETA')
GO